<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ClosedXML" Version="0.105.0" />
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="EPPlus" Version="8.5.1" />
		<PackageReference Include="ExcelDataReader" Version="3.8.0" />
		<PackageReference Include="ExcelDataReader.DataSet" Version="3.8.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.21" />
		<PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
		<PackageReference Include="NPOI" Version="2.7.6" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="System.DirectoryServices" Version="9.0.10" />
		<PackageReference Include="System.DirectoryServices.AccountManagement" Version="9.0.10" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Planeamiento\Programa-Mensual-Labores\Services\ExplotacionService\ModalsService\" />
		<Folder Include="Rutas\Data\Dto\" />
	</ItemGroup>

</Project>